# Generated by Django 2.1.7 on 2020-03-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='submissiont_date',
            new_name='submission_date',
        ),
    ]
